# Generated by Django 3.1.4 on 2021-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_status',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_Published',
            field=models.BooleanField(default=False),
        ),
    ]
