# Generated by Django 3.1.4 on 2021-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0004_auto_20210109_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
