# Generated by Django 3.1.4 on 2021-01-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0006_textfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextField',
            new_name='Text',
        ),
    ]
