# Generated by Django 3.1.4 on 2021-01-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0010_auto_20210109_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(upload_to='blog_img'),
        ),
    ]
