# Generated by Django 3.1.4 on 2021-01-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0011_auto_20210109_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
    ]
