# Generated by Django 3.1.4 on 2021-01-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0014_auto_20210110_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yaratici.blogpost'),
        ),
    ]
