# Generated by Django 3.1.4 on 2021-01-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0015_question_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='publish_date',
        ),
    ]
