# Generated by Django 3.1.4 on 2021-01-23 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0016_remove_question_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_Published', models.BooleanField(default=True)),
                ('photo', models.URLField(max_length=250)),
                ('youtube_link', models.URLField(max_length=250)),
            ],
        ),
    ]
