# Generated by Django 3.1.4 on 2021-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0017_challange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challange',
            name='youtube_link',
            field=models.CharField(max_length=500),
        ),
    ]
