# Generated by Django 3.1.4 on 2021-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0020_auto_20210203_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='asd'),
        ),
    ]
