# Generated by Django 3.1.4 on 2021-02-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0022_auto_20210203_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
