# Generated by Django 3.1.5 on 2021-02-07 11:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaratici', '0023_auto_20210203_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagineQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='imaginequestion_img')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_Published', models.BooleanField(default=False)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
