# Generated by Django 3.1.4 on 2021-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0024_imaginequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
