# Generated by Django 3.1.4 on 2021-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0002_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
