# Generated by Django 3.1.4 on 2021-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0003_choices_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
