# Generated by Django 3.1.4 on 2021-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0006_answers_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='email_img'),
        ),
    ]
