# Generated by Django 3.1.4 on 2021-01-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_Published',
        ),
    ]
