# Generated by Django 3.1.4 on 2021-01-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_challenge_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_Published',
            field=models.BooleanField(default=False),
        ),
    ]
