# Generated by Django 3.1.4 on 2021-01-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_challenge_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='image_likes',
        ),
    ]
