# Generated by Django 3.1.4 on 2021-01-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_imagenominate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenominate',
            name='photo',
            field=models.ImageField(upload_to='challenge_img/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
