# Generated by Django 3.1.4 on 2021-01-23 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0007_auto_20210124_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image_likes',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
