# Generated by Django 3.1.4 on 2021-01-23 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0008_challenge_image_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
