# Generated by Django 3.1.4 on 2021-01-24 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0009_auto_20210124_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='ChallengeParticipant',
        ),
    ]
