# Generated by Django 3.1.4 on 2021-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0014_auto_20210130_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenominate',
            name='owner',
            field=models.CharField(blank=True, max_length=150, verbose_name='Eser Sahibi 😊'),
        ),
    ]
