# Generated by Django 3.1.4 on 2021-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0015_imagenominate_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='score',
        ),
    ]
