# Generated by Django 3.1.4 on 2021-02-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0018_scoringactivities_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.challenge'),
        ),
    ]
