# Generated by Django 3.1.4 on 2021-02-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0019_scoreboard_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.comment'),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='imagenominate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamification.imagenominate'),
        ),
    ]
