# Generated by Django 3.1.4 on 2021-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0020_auto_20210204_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
