# Generated by Django 3.1.4 on 2021-02-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0021_scoreboard_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='imagenominate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.imagenominate'),
        ),
    ]
