# Generated by Django 3.1.5 on 2021-02-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaratici', '0023_auto_20210203_2045'),
        ('gamification', '0023_auto_20210204_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yaratici.blogpost'),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='weeklyquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yaratici.question'),
        ),
    ]
