# Generated by Django 3.1.5 on 2021-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0024_auto_20210205_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='totalscore',
            field=models.IntegerField(default=0),
        ),
    ]
