# Generated by Django 3.1.5 on 2021-02-13 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gamification.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0027_scoreboard_imaginequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(upload_to=gamification.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_img.jpg', upload_to=gamification.models.profile_directory_path),
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
