# Generated by Django 3.1.5 on 2021-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0028_auto_20210213_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.IntegerField(),
        ),
    ]
