# Generated by Django 3.1.5 on 2021-02-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0029_auto_20210213_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='childname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
